# Generated by Django 5.2.7 on 2025-11-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_classstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
