# Generated by Django 5.2.7 on 2025-11-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_classstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
